# Path to the main todo file
file_path: "/Users/chris.jansen/Dropbox/todo/todo.txt"
# Path to the archive file, for completed tasks
archive_file_path: "/Users/chris.jansen/Dropbox/todo/done.txt"
# Path to recurring file, for recurring tasks
recur_file_path: "/Users/chris.jansen/Dropbox/todo/recur.txt"
# Sort criteria
sort_type: Alphabetical 
# The current grouping
group_by_type: Project
# Boolean to indicate whether or not to add creation date to each new task
# add_creation_date: true
filter_text:
# Boolean to indicate whether or not debug logging is enabled
# debug_logging_on: true
debug_level: 1
list_on_start: true
list_after_command: false
display_before_threshold_date: false
